"""
Title: User Management
Date: 25/6/2021
Author: Chu Zhen Hao
Organisation: Malaysian Smart Factory 4.0 Team at Selangor Human Resource Development Centre (SHRDC)
"""

import sys
from pathlib import Path
SRC = Path(__file__).resolve().parents[1]  # ROOT folder -> ./src
LIB = sys.path.insert(0, str(Path(SRC, 'lib')))  # ./lib
print(LIB)

import logging
import psycopg2
from passlib.hash import argon2


#--------------------Logger-------------------------#

FORMAT = '[%(levelname)s] %(asctime)s - %(message)s'
DATEFMT = '%d-%b-%y %H:%M:%S'

# logging.basicConfig(filename='test.log',filemode='w',format=FORMAT, level=logging.DEBUG)
logging.basicConfig(format=FORMAT, level=logging.INFO,
                    stream=sys.stdout, datefmt=DATEFMT)

log = logging.getLogger()

#----------------------------------------------------#

# ------------------TEMP
import streamlit as st
from streamlit import cli as stcli  # Add CLI so can run Python script directly
# DEFINE Web APP page configuration
try:
    st.set_page_config(page_title="Integrated Vision Inspection System",
                       page_icon="static/media/shrdc_image/shrdc_logo.png", layout='wide')
except:
    st.beta_set_page_config(page_title="Label Studio Test",
                            page_icon="random", layout='wide')
# ------------------TEMP

conn = psycopg2.connect(
    "host=localhost port=5432 dbname=eye user=shrdc password=shrdc")

# Create Table


def createUsertable():
    # create relation : user_details
    create_username_table = """CREATE TABLE IF NOT EXISTS user_details (
                                user_id INT GENERATED BY DEFAULT AS IDENTITY, 
                                emp_id INT,
                                username TEXT NOT NULL, 
                                first_name TEXT,
                                last_name TEXT,
                                email TEXT, 
                                department TEXT,
                                position TEXT,                               
                                psd TEXT NOT NULL, 
                                role VARCHAR (30),
                                created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                last_activity TIMESTAMP WITH TIME ZONE,
                                PRIMARY KEY (user_id,role)
                                            );"""
    with conn:
        with conn.cursor() as cur:
            cur.execute(create_username_table)
            conn.commit()

# Create User


def createUser(new_user, **extra_fields):
    new_user = {}

    createUsertable()  # create user table if does not exist
    # Employee Corporate Details
    log.info("User Entry")
    new_user["emp_id"] = input("Employee ID: ")
    new_user["first_name"] = input("First Name: ")
    new_user["last_name"] = input("Last Name: ")
    new_user["email"] = input("Employee Email: ")
    new_user["department"] = input("Department: ")
    new_user["position"] = input("Position: ")

    # Account Corporate Details
    new_user["username"] = input("Username: ")
    new_user["role"] = input("Role: ")
    new_user["psd"] = argon2.hash(input("Password: "))
    log.info(f'password: {new_user["psd"]}')

    with conn:
        with conn.cursor() as cur:
            cur.execute(""" INSERT INTO user_details (emp_id,first_name,last_name,email,department,position,username,role, psd) 
                            VALUES (%s,%s, %s,%s,%s,%s,%s,%s,%s)
                            RETURNING user_id,username,created_at as create_user;""",
                        [new_user["emp_id"], new_user["first_name"], new_user["last_name"], new_user["email"], new_user["department"], new_user["position"],
                         new_user["username"], new_user["role"], new_user["psd"]])
            # cur.execute("select * from Login;")
            conn.commit()
            user_create = cur.fetchone()
            log.info(user_create)
            new_user = {}
    return user_create


# User Login

def userLogin(username, psd, **extra_fields):
    user_login = {}
    user_login["username"] = input("Username: ")
    user_login["password"] = input("Password: ")
    print(f'Login password: {user_login["password"]}')

    with conn:
        with conn.cursor() as cur:
            cur.execute("SELECT psd FROM Login where username=%s;",
                        [user_login["username"]])

            conn.commit()
            user_success = cur.fetchone()
            print(user_success)

    return user_login, user_success


old_user, rows = userLogin()  # Create New User

if rows is not None:
    password = rows[0][0]
    print(f"Retrieved password: {password}")
    print(argon2.verify(old_user["password"], password))


user_create = createUser()  # Create New User


conn.close()
