-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE IF NOT EXISTS eye
OWNER shrdc
TABLESPACE shrdcdb;



CREATE TABLE public."user"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    emp_id text,
    username text NOT NULL,
    first_name text,
    last_name text,
    email text,
    department text,
    "position" text,
    psd text NOT NULL,
    role_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    last_activity timestamp with time zone,
    status character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.role
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    page_access_list text[],
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.training
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    training_param jsonb[],
    augmentation jsonb[],
    model_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    pre_trained_model_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.session_log
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    login_at timestamp with time zone NOT NULL,
    logout_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.training_log
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    training_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.pre_trained_models
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.models
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    model_name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.predictions
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    results jsonb[],
    deployment_type character varying(100) NOT NULL,
    model_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    pre_trained_model_id bigint,
    score double precision,
    user_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.dataset
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dataset_path text NOT NULL,
    dataset_size integer,
    file_type character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.project
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    description text,
    deployment_type character varying(100),
    editor_config text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dataset_id bigint,
    training_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.task
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dataset_id bigint NOT NULL,
    annotation_id bigint,
    prediction_id aclitem,
    is_labeled boolean NOT NULL,
    skip boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.annotations
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    results jsonb[],
    deployment_type character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    task_id bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.session_log
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id)
    NOT VALID;


ALTER TABLE public."user"
    ADD FOREIGN KEY (role_id)
    REFERENCES public.role (id)
    NOT VALID;


ALTER TABLE public.training_log
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id)
    NOT VALID;


ALTER TABLE public.training_log
    ADD FOREIGN KEY (training_id)
    REFERENCES public.training (id)
    NOT VALID;


ALTER TABLE public.training
    ADD FOREIGN KEY (pre_trained_model_id)
    REFERENCES public.pre_trained_models (id)
    NOT VALID;


ALTER TABLE public.predictions
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id)
    NOT VALID;


ALTER TABLE public.predictions
    ADD FOREIGN KEY (model_id)
    REFERENCES public.models (id)
    NOT VALID;


ALTER TABLE public.project
    ADD FOREIGN KEY (dataset_id)
    REFERENCES public.dataset (id)
    NOT VALID;


ALTER TABLE public.project
    ADD FOREIGN KEY (training_id)
    REFERENCES public.training (id)
    NOT VALID;


ALTER TABLE public.task
    ADD FOREIGN KEY (dataset_id)
    REFERENCES public.dataset (id)
    NOT VALID;


ALTER TABLE public.task
    ADD FOREIGN KEY (prediction_id)
    REFERENCES public.predictions (id)
    NOT VALID;


ALTER TABLE public.annotations
    ADD FOREIGN KEY (user_id)
    REFERENCES public."user" (id)
    NOT VALID;


ALTER TABLE public.annotations
    ADD FOREIGN KEY (task_id)
    REFERENCES public.task (id)
    NOT VALID;


ALTER TABLE public.annotations
    ADD FOREIGN KEY (project_id)
    REFERENCES public.project (id)
    NOT VALID;

END;