-- Title: Integrated Vision Inspection System
-- Date:10/7/2021
-- Author: Chu Zhen Hao
--  Organisation: Malaysian Smart Factory 4.0 Team at Selangor Human Resource Development Centre (SHRDC)
BEGIN;

CREATE ROLE integrated_vision_inspection_system WITH superuser createdb createrole noinherit encrypted PASSWORD 'integrated_vision_inspection_system';

CREATE TABLESPACE IF NOT EXISTS integrated_vision_inspection_system OWNER integrated_vision_inspection_system location '$HOME/.local/share/integrated_vision_inspection_system';

-- CREATE DATABASE IF NOT EXISTS integrated_vision_inspection_system OWNER integrated_vision_inspection_system TABLESPACE integrated_vision_inspection_system;
-- CREATE DATABASE IF NOT EXISTS eye OWNER shrdc TABLESPACE shrdcdb;
CREATE DATABASE IF NOT EXISTS eye OWNER shrdc TABLESPACE image_labelling;

-- Trigger Function for Update Time
CREATE OR REPLACE FUNCTION trigger_update_timestamp ()
    RETURNS TRIGGER
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;

ALTER FUNCTION public.trigger_update_timestamp () OWNER TO shrdc;

-- USERS table ------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    emp_id text UNIQUE,
    username text NOT NULL UNIQUE,
    first_name text,
    last_name text,
    email text,
    department text,
    position text,
    psd text NOT NULL,
    roles_id integer NOT NULL,
    account_status character varying(30) NOT NULL CHECK (account_status IN ('NEW', 'ACTIVE', 'LOCKED', 'LOGGED_IN', 'LOGGED_OUT')),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity timestamp with time zone,
    PRIMARY KEY (id),
    CONSTRAINT fk_roles_id FOREIGN KEY (roles_id) REFERENCES public.roles (id) ON DELETE SET NULL)
TABLESPACE image_labelling;

CREATE TRIGGER users_update
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_update_timestamp ();

--  ROW table --------------------------------------------------
CREATE TABLE public.roles (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    name character varying(50) NOT NULL,
    page_access_list text[],
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id))
TABLESPACE image_labelling;

ALTER TABLE public.roles OWNER TO shrdc;

CREATE TRIGGER roles_update
    BEFORE UPDATE ON public.roles
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_update_timestamp ();

-- INSERT pre-defined values into ROLES
INSERT INTO public.roles (
    name,
    page_access_list)
VALUES (
    'Administrator',
    ARRAY['Login', 'Project', 'Dataset', 'Editor', 'Model Training', 'Deployment', 'User Management']),
(
    'Developer 1 (Deployment)',
    ARRAY['Login', 'Project', 'Dataset', 'Editor', 'Model Training', 'Deployment']),
(
    'Developer 2 (Model Training)',
    ARRAY['Login', 'Project', 'Dataset', 'Editor', 'Model Training']),
(
    'Annotator',
    ARRAY['Login', 'Project', 'Dataset', 'Editor']);

--  SESSION_LOG table --------------------------------------------------
CREATE TABLE public.session_log (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (CYCLE INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    users_id bigint NOT NULL,
    login_at timestamp with time zone NOT NULL,
    logout_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_users_id FOREIGN KEY (users_id) REFERENCES public.users (id) ON DELETE NO ACTION)
TABLESPACE image_labelling;

--  PROJECT table --------------------------------------------------
CREATE TABLE public.project (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    name text NOT NULL,
    description text,
    deployment_id integer,
    dataset_id bigint,
    training_id bigint,
    editor_config text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_deployment_id FOREIGN KEY (deployment_id) REFERENCES public.deployment_type (id) ON DELETE SET NULL,
    CONSTRAINT fk_training_id FOREIGN KEY (training_id) REFERENCES public.training (id) ON DELETE SET NULL)
TABLESPACE image_labelling;

CREATE TRIGGER project_update
    BEFORE UPDATE ON public.project
    FOR EACH ROW
    EXECUTE PROCEDURE trigger_update_timestamp ();

--  TRAINING table --------------------------------------------------
CREATE TABLE public.training (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    name text NOT NULL,
    training_param jsonb[],
    augmentation jsonb[],
    model_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    pre_trained_model_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.training_log (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (CYCLE INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    users_id bigint NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    training_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.pre_trained_models (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (CYCLE INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.models (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    model_name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE public.predictions (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    results jsonb[],
    deployment_type character varying(100) NOT NULL,
    model_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    pre_trained_model_id bigint,
    score double precision,
    users_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.dataset (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    name text NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dataset_path text NOT NULL,
    dataset_size integer,
    file_type character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.task (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    name text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    dataset_id bigint NOT NULL,
    annotation_id bigint,
    prediction_id aclitem,
    is_labeled boolean NOT NULL,
    skip boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.annotations (
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY (INCREMENT 1 START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1),
    results jsonb[],
    deployment_type character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    project_id bigint NOT NULL,
    users_id bigint NOT NULL,
    task_id bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.session_log
    ADD FOREIGN KEY (users_id) REFERENCES public.users (id) NOT VALID;

ALTER TABLE public.training_log
    ADD FOREIGN KEY (users_id) REFERENCES public.users (id) NOT VALID;

ALTER TABLE public.training_log
    ADD FOREIGN KEY (training_id) REFERENCES public.training (id) NOT VALID;

ALTER TABLE public.training
    ADD FOREIGN KEY (pre_trained_model_id) REFERENCES public.pre_trained_models (id) NOT VALID;

ALTER TABLE public.predictions
    ADD FOREIGN KEY (users_id) REFERENCES public.users (id) NOT VALID;

ALTER TABLE public.predictions
    ADD FOREIGN KEY (model_id) REFERENCES public.models (id) NOT VALID;

ALTER TABLE public.project
    ADD FOREIGN KEY (dataset_id) REFERENCES public.dataset (id) NOT VALID;

ALTER TABLE public.project
    ADD FOREIGN KEY (training_id) REFERENCES public.training (id) NOT VALID;

ALTER TABLE public.task
    ADD FOREIGN KEY (dataset_id) REFERENCES public.dataset (id) NOT VALID;

ALTER TABLE public.task
    ADD FOREIGN KEY (prediction_id) REFERENCES public.predictions (id) NOT VALID;

ALTER TABLE public.annotations
    ADD FOREIGN KEY (users_id) REFERENCES public.users (id) NOT VALID;

ALTER TABLE public.annotations
    ADD FOREIGN KEY (task_id) REFERENCES public.task (id) NOT VALID;

ALTER TABLE public.annotations
    ADD FOREIGN KEY (project_id) REFERENCES public.project (id) NOT VALID;

END;

