"""
Title: User Management
Date: 25/6/2021
Author: Chu Zhen Hao
Organisation: Malaysian Smart Factory 4.0 Team at Selangor Human Resource Development Centre (SHRDC)
"""

import sys
from pathlib import Path
from typing import Union, List
import psycopg2
from PIL import Image
from time import sleep
from enum import IntEnum
import streamlit as st
from streamlit import cli as stcli  # Add CLI so can run Python script directly
from streamlit import session_state as SessionState

# >>>>>>>>>>>>>>>>>>>>>>TEMP>>>>>>>>>>>>>>>>>>>>>>>>

SRC = Path(__file__).resolve().parents[2]  # ROOT folder -> ./src
LIB_PATH = SRC / "lib"

if str(LIB_PATH) not in sys.path:
    sys.path.insert(0, str(LIB_PATH))  # ./lib
else:
    pass

# >>>> User-defined Modules >>>>
from path_desc import chdir_root
from core.utils.log import log_info, log_error  # logger
from data_manager.database_manager import init_connection, db_fetchone, db_no_fetch
from core.utils.file_handler import bytes_divisor, create_folder_if_not_exist
from core.utils.helper import split_string, join_string
# <<<<<<<<<<<<<<<<<<<<<<TEMP<<<<<<<<<<<<<<<<<<<<<<<

# >>>> Variable Declaration >>>>

# initialise connection to Database
conn = init_connection(**st.secrets["postgres"])


class account_status(IntEnum):
    # **** User Status ****

    NEW = 0  # Pending account activation
    ACTIVE = 1  # Account activated
    LOCKED = 2  # Account locked
    LOGGED_IN = 3  # Account logged-in
    LOGGED_OUT = 4  # Account logged-out


# <<<< Variable Declaration <<<<


# TODO: move to form_manager
def check_if_field_empty(new_user, field_placeholder, field_name):
    empty_fields = []
    # all_field_filled = all(new_user)
    # if not all_field_filled:  # IF there are blank fields, iterate and produce error message
    for key, value in new_user.items():
        if value == "":
            field_placeholder[key].error(
                f"Please do not leave {field_name[key]} field blank")
            empty_fields.append(key)

        else:
            pass

    return not empty_fields

# TODO:KIV can be removed


def create_project_table(conn=conn):  # Create Table
    # create relation : user_details
    create_project_table_SQL = """
                                CREATE TABLE IF NOT EXISTS public.project (
                                id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 START 1
                                MINVALUE 1
                                MAXVALUE 9223372036854775807
                                CACHE 1),
                                name text NOT NULL UNIQUE,
                                description text,
                                deployment_id integer,
                                dataset_id bigint,
                                training_id bigint,
                                editor_config text,
                                created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (id),
                                CONSTRAINT fk_deployment_id FOREIGN KEY (deployment_id) REFERENCES public.deployment_type (id) ON DELETE SET NULL,
                                CONSTRAINT fk_training_id FOREIGN KEY (training_id) REFERENCES public.training (id) ON DELETE SET NULL)
                            TABLESPACE image_labelling;

                            CREATE TRIGGER project_update
                                BEFORE UPDATE ON public.project
                                FOR EACH ROW
                                EXECUTE PROCEDURE trigger_update_timestamp ();

                            ALTER TABLE public.project OWNER TO shrdc;
                            """
    db_no_fetch(create_project_table_SQL, conn)

# >>>> CREATE PROJECT >>>>


def insert_dataset(self):
    insert_dataset_SQL = """
                                INSERT INTO public.dataset (
                                    name,
                                    description,
                                    file_type,
                                    dataset_path,
                                    dataset_size,
                                    deployment_id)
                                VALUES (
                                    %s,
                                    %s,
                                    %s,
                                    %s,
                                    %s,
                                    %s)
                                RETURNING id;
                            """
    insert_dataset_vars = [self.name, self.desc, self.file_type,
                           str(self.dataset_path), self.dataset_size, self.deployment_id]
    self.dataset_id = db_fetchone(
        insert_dataset_SQL, insert_dataset_vars, conn)
    return self.dataset_id


def main():
    print("Hi")


if __name__ == "__main__":
    if st._is_running_with_streamlit:
        main()
    else:
        sys.argv = ["streamlit", "run", sys.argv[0]]
        sys.exit(stcli.main())
